TRAIN:
    model: resnet50
    N: 2
    M: 4
    sparse_optimizer: 1

    workers: 3
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.00005


    print_freq: 100
    model_dir: checkpoint/resnet50_2:4

    train_root: /mnt/lustre/share/images/train
    train_source: /mnt/lustre/share/images/meta/train.txt
    val_root: /mnt/lustre/share/images/val
    val_source: /mnt/lustre/share/images/meta/val.txt




TEST:
    checkpoint_path : data/pretrained_model/
